// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKTAgoIWt4aEQFWZT3j_52MoUuBkjt4hw',
    appId: '1:706787444424:web:8925de100ebe4a9fee07fd',
    messagingSenderId: '706787444424',
    projectId: 'fire-base-project-1e4e3',
    authDomain: 'fire-base-project-1e4e3.firebaseapp.com',
    storageBucket: 'fire-base-project-1e4e3.appspot.com',
    measurementId: 'G-1Z2CQFVF1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJUfYGDlw08hQ2Xw_j2rJuNjfMP0uii9o',
    appId: '1:706787444424:android:0faab92d88ba8bf0ee07fd',
    messagingSenderId: '706787444424',
    projectId: 'fire-base-project-1e4e3',
    storageBucket: 'fire-base-project-1e4e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOebuZ-N0tdaLecXrEbXbWY1Bm6Egw0U',
    appId: '1:706787444424:ios:ad758f781146d7cdee07fd',
    messagingSenderId: '706787444424',
    projectId: 'fire-base-project-1e4e3',
    storageBucket: 'fire-base-project-1e4e3.appspot.com',
    iosBundleId: 'com.example.rdpToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVOebuZ-N0tdaLecXrEbXbWY1Bm6Egw0U',
    appId: '1:706787444424:ios:ad758f781146d7cdee07fd',
    messagingSenderId: '706787444424',
    projectId: 'fire-base-project-1e4e3',
    storageBucket: 'fire-base-project-1e4e3.appspot.com',
    iosBundleId: 'com.example.rdpToDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKTAgoIWt4aEQFWZT3j_52MoUuBkjt4hw',
    appId: '1:706787444424:web:3b27dc3fe382c2a1ee07fd',
    messagingSenderId: '706787444424',
    projectId: 'fire-base-project-1e4e3',
    authDomain: 'fire-base-project-1e4e3.firebaseapp.com',
    storageBucket: 'fire-base-project-1e4e3.appspot.com',
    measurementId: 'G-KJ3C8BJC6J',
  );
}
